New Autograder
Cal-CS-61A-Staff/cs61a-apps pull request #232
Opened 2021-01-29 20:46 UTC by itsvs

2021-02-01 22:22 UTC, rahularya50 requested changes

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/Dockerfile
> +FROM python:buster
no need for the dockerfile

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/.gitignore
> +zips
?

2021-02-01 22:22 UTC, rahularya50 commented on ag-worker/common
> +../common
y?

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +WORKER_URL = "https://232.ag-worker.pr.cs61a.org"
reminder to fix / replace with rpc eventually

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +## Relevant Decorators
use a separate file, not this commenting stuff

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +    id = gen_salt(24)
use `new_secret()` from common

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +    assignments = Assignment.query.filter_by(course=course.secret)
don't you need to `.all()` here? It 500s when I visit the page. Also might be nice to make this the index page

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +## Okpy Endpoints
\clap new file

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +        return "OK"
?

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +        requests.post(
rpc!

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +    subm_batches = [subms[i : i + 100] for i in range(0, len(subms), 100)]
100 should be a constant at the top of the file, so we know everywhere it's used

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +        print("requesting " + SUBM_ENDPOINT + "/" + str(id), file=sys.stderr)
rm

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +    if job and assignment:
does not validate! You need to check that the query has an output - queries on their own are always truthy, I think

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +    )  # validates secret
same

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +    if job and assignment:
though technically the job_id, being secret, is enough

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +def index():
rm

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/main.py
> +    os.makedirs(f"./zips/{name}-{sem}/")
?

2021-02-01 22:22 UTC, rahularya50 commented on ag-master/models.py
> +    semester: str = db.Column(db.String(64))
useless column

2021-02-01 22:23 UTC, itsvs commented on ag-master/main.py
> +        return "OK"
backwards compatibility with okpy

2021-02-01 23:25 UTC, itsvs commented on ag-worker/common
> +../common
for rpc (coming soon)

2021-02-02 03:38 UTC, rahularya50 commented on ag-master/superadmin.py
> +def create_superadmin_endpoints(app, db):
can't you just import `db`? Why is it passed in as an arg?

2021-02-07 06:10 UTC, merged